import type {
  Capability,
  Criticality,
  MetricCategory,
  MetricDefinition,
} from "@/lib/types";

/** Base weight derived from criticality (SCORING_MODEL effective_weight input). */
export const CRITICALITY_WEIGHT: Record<Criticality, number> = {
  Critical: 10,
  High: 6,
  Medium: 3,
  Low: 1,
};

/** Severity contribution used by the risk engine. */
export const CRITICALITY_SEVERITY: Record<Criticality, number> = {
  Critical: 1.0,
  High: 0.7,
  Medium: 0.45,
  Low: 0.2,
};

const METRIC_VERSION = "2026.07.0";

type CatalogRow = {
  id: string;
  name: string;
  category: MetricCategory;
  capability: Capability;
  source: string;
  target: string;
  criticality: Criticality;
  freshnessThresholdHours: number;
  ownerRole: string;
  populationBased: boolean;
  businessRisk: string;
  remediation: string;
};

/**
 * Initial production metric set (METRIC_CATALOG.md). Every entry is versioned and
 * customer-configurable via CustomerMetricConfiguration overrides.
 */
const ROWS: CatalogRow[] = [
  // Identity ---------------------------------------------------------------
  {
    id: "IDENTITY-001",
    name: "Privileged MFA Coverage",
    category: "Security",
    capability: "identity_security",
    source: "Microsoft Graph / Entra ID",
    target: "100%",
    criticality: "Critical",
    freshnessThresholdHours: 24,
    ownerRole: "Security Engineer",
    populationBased: true,
    businessRisk: "Unprotected admin accounts enable full tenant takeover.",
    remediation: "Enforce MFA on all privileged roles via Conditional Access.",
  },
  {
    id: "IDENTITY-002",
    name: "User MFA Coverage",
    category: "Security",
    capability: "identity_security",
    source: "Microsoft Graph / Entra ID",
    target: "98%",
    criticality: "High",
    freshnessThresholdHours: 24,
    ownerRole: "Security Engineer",
    populationBased: true,
    businessRisk: "Accounts without MFA are the top vector for account compromise.",
    remediation: "Roll out MFA registration campaign and enforce via policy.",
  },
  {
    id: "IDENTITY-003",
    name: "Legacy Authentication Blocked",
    category: "Security",
    capability: "identity_security",
    source: "Microsoft Graph / Entra ID",
    target: "100%",
    criticality: "High",
    freshnessThresholdHours: 24,
    ownerRole: "Security Engineer",
    populationBased: false,
    businessRisk: "Legacy auth bypasses MFA and enables password spray.",
    remediation: "Block legacy authentication protocols with Conditional Access.",
  },
  {
    id: "IDENTITY-004",
    name: "Stale Privileged Accounts",
    category: "Security",
    capability: "identity_security",
    source: "Microsoft Graph / Entra ID",
    target: "0",
    criticality: "High",
    freshnessThresholdHours: 48,
    ownerRole: "Security Engineer",
    populationBased: false,
    businessRisk: "Dormant admin accounts expand attack surface.",
    remediation: "Disable or remove unused privileged accounts.",
  },
  {
    id: "IDENTITY-005",
    name: "Risky Sign-ins Unresolved",
    category: "Security",
    capability: "identity_security",
    source: "Microsoft Defender / Entra ID",
    target: "0 critical",
    criticality: "Critical",
    freshnessThresholdHours: 12,
    ownerRole: "Security Engineer",
    populationBased: false,
    businessRisk: "Unresolved risky sign-ins may indicate active compromise.",
    remediation: "Investigate and remediate flagged sign-ins; reset credentials.",
  },
  // M365 ------------------------------------------------------------------
  {
    id: "M365-001",
    name: "Secure Score Relative Posture",
    category: "Security",
    capability: "m365_security",
    source: "Microsoft 365",
    target: "Baseline target",
    criticality: "Medium",
    freshnessThresholdHours: 72,
    ownerRole: "Security Engineer",
    populationBased: false,
    businessRisk: "Below-baseline posture indicates missing hardening controls.",
    remediation: "Action highest-impact Secure Score recommendations.",
  },
  {
    id: "M365-002",
    name: "External Forwarding Controls",
    category: "Security",
    capability: "m365_security",
    source: "Microsoft 365",
    target: "100% controlled",
    criticality: "High",
    freshnessThresholdHours: 48,
    ownerRole: "Security Engineer",
    populationBased: false,
    businessRisk: "Auto-forwarding rules exfiltrate mail in BEC attacks.",
    remediation: "Block external auto-forwarding via transport rules.",
  },
  {
    id: "M365-003",
    name: "Anti-phishing Policy Coverage",
    category: "Security",
    capability: "m365_security",
    source: "Microsoft Defender",
    target: "100%",
    criticality: "High",
    freshnessThresholdHours: 72,
    ownerRole: "Security Engineer",
    populationBased: true,
    businessRisk: "Uncovered mailboxes are exposed to phishing and impersonation.",
    remediation: "Extend anti-phishing policy to all mailboxes.",
  },
  {
    id: "M365-004",
    name: "Mailbox Audit Coverage",
    category: "Security",
    capability: "m365_security",
    source: "Microsoft 365",
    target: "100%",
    criticality: "Medium",
    freshnessThresholdHours: 72,
    ownerRole: "Security Engineer",
    populationBased: true,
    businessRisk: "Without mailbox auditing, BEC investigations lack evidence.",
    remediation: "Enable mailbox audit logging tenant-wide.",
  },
  // EDR -------------------------------------------------------------------
  {
    id: "EDR-001",
    name: "CrowdStrike Sensor Coverage",
    category: "Security",
    capability: "edr",
    source: "CrowdStrike",
    target: "99%",
    criticality: "Critical",
    freshnessThresholdHours: 12,
    ownerRole: "Security Engineer",
    populationBased: true,
    businessRisk: "Endpoints without EDR are blind spots for attackers.",
    remediation: "Deploy CrowdStrike sensor to uncovered endpoints.",
  },
  {
    id: "EDR-002",
    name: "CrowdStrike Sensor Health",
    category: "Security",
    capability: "edr",
    source: "CrowdStrike",
    target: "99%",
    criticality: "Critical",
    freshnessThresholdHours: 12,
    ownerRole: "Security Engineer",
    populationBased: true,
    businessRisk: "Unhealthy sensors silently stop protecting endpoints.",
    remediation: "Repair or reinstall sensors reporting degraded state.",
  },
  {
    id: "EDR-003",
    name: "Defender Device Health",
    category: "Security",
    capability: "edr",
    source: "Microsoft Defender",
    target: "98%",
    criticality: "High",
    freshnessThresholdHours: 24,
    ownerRole: "Security Engineer",
    populationBased: true,
    businessRisk: "Devices with disabled protection are exposed to malware.",
    remediation: "Remediate Defender health issues and re-enable protection.",
  },
  {
    id: "EDR-004",
    name: "Critical EDR Detections Open",
    category: "Security",
    capability: "edr",
    source: "CrowdStrike / Defender",
    target: "0",
    criticality: "Critical",
    freshnessThresholdHours: 6,
    ownerRole: "Security Engineer",
    populationBased: false,
    businessRisk: "Open critical detections may indicate an active intrusion.",
    remediation: "Triage and contain critical detections immediately.",
  },
  // Huntress --------------------------------------------------------------
  {
    id: "HUNTRESS-001",
    name: "Huntress Agent Coverage",
    category: "Security",
    capability: "mdr",
    source: "Huntress",
    target: "98%",
    criticality: "High",
    freshnessThresholdHours: 24,
    ownerRole: "Security Engineer",
    populationBased: true,
    businessRisk: "Endpoints without Huntress lack persistence detection.",
    remediation: "Deploy Huntress agent to uncovered endpoints.",
  },
  {
    id: "HUNTRESS-002",
    name: "Huntress Incident Age",
    category: "Security",
    capability: "mdr",
    source: "Huntress",
    target: "Within SLA",
    criticality: "Critical",
    freshnessThresholdHours: 6,
    ownerRole: "Security Engineer",
    populationBased: false,
    businessRisk: "Aging incidents allow attacker dwell time to grow.",
    remediation: "Investigate and remediate open Huntress incidents.",
  },
  // Patch -----------------------------------------------------------------
  {
    id: "PATCH-001",
    name: "Critical Patch Compliance",
    category: "Reliability",
    capability: "endpoint_management",
    source: "NinjaOne",
    target: "98%",
    criticality: "High",
    freshnessThresholdHours: 24,
    ownerRole: "Support Engineer",
    populationBased: true,
    businessRisk: "Unpatched critical vulnerabilities are readily exploited.",
    remediation: "Approve and deploy outstanding critical patches.",
  },
  {
    id: "PATCH-002",
    name: "Unsupported Operating Systems",
    category: "Reliability",
    capability: "endpoint_management",
    source: "NinjaOne",
    target: "0",
    criticality: "Critical",
    freshnessThresholdHours: 48,
    ownerRole: "Service Manager",
    populationBased: true,
    businessRisk: "End-of-life OSes no longer receive security updates.",
    remediation: "Plan and execute OS upgrade or replacement.",
  },
  // Device ----------------------------------------------------------------
  {
    id: "DEVICE-001",
    name: "RMM Agent Coverage",
    category: "Coverage",
    capability: "endpoint_management",
    source: "NinjaOne",
    target: "99%",
    criticality: "High",
    freshnessThresholdHours: 12,
    ownerRole: "Support Engineer",
    populationBased: true,
    businessRisk: "Unmanaged devices cannot be patched or monitored.",
    remediation: "Install RMM agent on discovered but unmanaged devices.",
  },
  {
    id: "DEVICE-002",
    name: "Devices Offline Beyond Threshold",
    category: "Reliability",
    capability: "endpoint_management",
    source: "NinjaOne",
    target: "<2%",
    criticality: "Medium",
    freshnessThresholdHours: 12,
    ownerRole: "Support Engineer",
    populationBased: true,
    businessRisk: "Long-offline devices may be lost, stolen, or failing.",
    remediation: "Investigate persistently offline devices.",
  },
  {
    id: "DEVICE-003",
    name: "Low Disk Space",
    category: "Reliability",
    capability: "endpoint_management",
    source: "NinjaOne",
    target: "0 critical",
    criticality: "Medium",
    freshnessThresholdHours: 12,
    ownerRole: "Support Engineer",
    populationBased: true,
    businessRisk: "Full disks cause outages and failed updates.",
    remediation: "Free space or expand storage on affected devices.",
  },
  {
    id: "DEVICE-004",
    name: "Disk SMART Alerts",
    category: "Reliability",
    capability: "endpoint_management",
    source: "NinjaOne",
    target: "0",
    criticality: "High",
    freshnessThresholdHours: 24,
    ownerRole: "Support Engineer",
    populationBased: false,
    businessRisk: "SMART alerts predict imminent drive failure and data loss.",
    remediation: "Replace drives reporting SMART failures.",
  },
  // Backup ----------------------------------------------------------------
  {
    id: "BACKUP-001",
    name: "Protected System Coverage",
    category: "Reliability",
    capability: "backup",
    source: "MSP360",
    target: "100%",
    criticality: "Critical",
    freshnessThresholdHours: 24,
    ownerRole: "Service Manager",
    populationBased: true,
    businessRisk: "Unprotected systems cannot be recovered after an incident.",
    remediation: "Onboard unprotected critical systems to backup.",
  },
  {
    id: "BACKUP-002",
    name: "Successful Backup Jobs",
    category: "Reliability",
    capability: "backup",
    source: "MSP360",
    target: "98%",
    criticality: "Critical",
    freshnessThresholdHours: 24,
    ownerRole: "Service Manager",
    populationBased: true,
    businessRisk: "Failing backups mean no recovery point during ransomware.",
    remediation: "Diagnose and rerun failing backup jobs.",
  },
  {
    id: "BACKUP-003",
    name: "Backup Failure Age",
    category: "Reliability",
    capability: "backup",
    source: "MSP360",
    target: "<24h",
    criticality: "Critical",
    freshnessThresholdHours: 12,
    ownerRole: "Service Manager",
    populationBased: false,
    businessRisk: "The longer a backup stays failed, the larger the data-loss window.",
    remediation: "Restore backup service and confirm a clean job.",
  },
  {
    id: "BACKUP-004",
    name: "Restore Test Currency",
    category: "Reliability",
    capability: "backup",
    source: "MSP360 / manual",
    target: "<90 days",
    criticality: "High",
    freshnessThresholdHours: 24 * 90,
    ownerRole: "Service Manager",
    populationBased: false,
    businessRisk: "Untested restores may silently fail when needed most.",
    remediation: "Perform and document a restore test.",
  },
  // Halo ------------------------------------------------------------------
  {
    id: "HALO-001",
    name: "Critical Ticket First Response",
    category: "Experience",
    capability: "service_management",
    source: "HaloPSA",
    target: "Within SLA",
    criticality: "High",
    freshnessThresholdHours: 6,
    ownerRole: "Service Manager",
    populationBased: false,
    businessRisk: "Slow first response breaches SLA and erodes trust.",
    remediation: "Rebalance queue staffing and triage critical tickets first.",
  },
  {
    id: "HALO-002",
    name: "Critical Ticket Age",
    category: "Experience",
    capability: "service_management",
    source: "HaloPSA",
    target: "Within SLA",
    criticality: "High",
    freshnessThresholdHours: 6,
    ownerRole: "Service Manager",
    populationBased: false,
    businessRisk: "Aging critical tickets signal unresolved customer pain.",
    remediation: "Escalate and resolve aged critical tickets.",
  },
  {
    id: "HALO-003",
    name: "Reopened Ticket Rate",
    category: "Experience",
    capability: "service_management",
    source: "HaloPSA",
    target: "<5%",
    criticality: "Medium",
    freshnessThresholdHours: 48,
    ownerRole: "Service Manager",
    populationBased: false,
    businessRisk: "High reopen rates indicate incomplete fixes.",
    remediation: "Review closure quality and root-cause reopened tickets.",
  },
  {
    id: "HALO-004",
    name: "Repeat Incident Rate",
    category: "Experience",
    capability: "service_management",
    source: "HaloPSA",
    target: "Downward trend",
    criticality: "High",
    freshnessThresholdHours: 48,
    ownerRole: "Service Manager",
    populationBased: false,
    businessRisk: "Repeat incidents indicate unaddressed root causes.",
    remediation: "Open problem records and pursue durable fixes.",
  },
  {
    id: "HALO-005",
    name: "CSAT",
    category: "Experience",
    capability: "service_management",
    source: "HaloPSA",
    target: ">=95%",
    criticality: "Medium",
    freshnessThresholdHours: 72,
    ownerRole: "Account Manager",
    populationBased: false,
    businessRisk: "Declining CSAT is a leading indicator of churn.",
    remediation: "Follow up on low-satisfaction interactions.",
  },
  // IT Glue ---------------------------------------------------------------
  {
    id: "ITGLUE-001",
    name: "Required Documentation Coverage",
    category: "Coverage",
    capability: "documentation",
    source: "IT Glue",
    target: ">=95%",
    criticality: "Medium",
    freshnessThresholdHours: 24 * 30,
    ownerRole: "Service Manager",
    populationBased: true,
    businessRisk: "Missing documentation slows recovery and onboarding.",
    remediation: "Complete required documentation records.",
  },
  {
    id: "ITGLUE-002",
    name: "Critical Runbook Currency",
    category: "Coverage",
    capability: "documentation",
    source: "IT Glue",
    target: "<180 days",
    criticality: "High",
    freshnessThresholdHours: 24 * 180,
    ownerRole: "Service Manager",
    populationBased: false,
    businessRisk: "Stale runbooks fail during real incidents.",
    remediation: "Review and update critical runbooks.",
  },
  {
    id: "ITGLUE-003",
    name: "Asset Record Reconciliation",
    category: "Coverage",
    capability: "documentation",
    source: "IT Glue",
    target: ">=95%",
    criticality: "Medium",
    freshnessThresholdHours: 24 * 7,
    ownerRole: "Service Manager",
    populationBased: true,
    businessRisk: "Documentation drift from reality misleads responders.",
    remediation: "Reconcile IT Glue asset records with discovered assets.",
  },
  // Network ---------------------------------------------------------------
  {
    id: "NETWORK-001",
    name: "Managed Gateway Availability",
    category: "Reliability",
    capability: "network_management",
    source: "UniFi / Meraki",
    target: ">=99.9%",
    criticality: "High",
    freshnessThresholdHours: 6,
    ownerRole: "Support Engineer",
    populationBased: false,
    businessRisk: "Gateway downtime takes the customer offline.",
    remediation: "Investigate gateway stability and ISP health.",
  },
  {
    id: "NETWORK-002",
    name: "Network Device Firmware Compliance",
    category: "Security",
    capability: "network_management",
    source: "UniFi / Meraki",
    target: ">=95%",
    criticality: "Medium",
    freshnessThresholdHours: 24 * 7,
    ownerRole: "Support Engineer",
    populationBased: true,
    businessRisk: "Outdated firmware carries known vulnerabilities.",
    remediation: "Schedule firmware upgrades on lagging devices.",
  },
  {
    id: "NETWORK-003",
    name: "Critical Network Alerts Open",
    category: "Reliability",
    capability: "network_management",
    source: "UniFi / Meraki",
    target: "0",
    criticality: "High",
    freshnessThresholdHours: 6,
    ownerRole: "Support Engineer",
    populationBased: false,
    businessRisk: "Open critical alerts precede outages.",
    remediation: "Resolve outstanding critical network alerts.",
  },
  {
    id: "NETWORK-004",
    name: "Network Management Coverage",
    category: "Coverage",
    capability: "network_management",
    source: "UniFi / Meraki",
    target: ">=98%",
    criticality: "High",
    freshnessThresholdHours: 24,
    ownerRole: "Support Engineer",
    populationBased: true,
    businessRisk: "Unmanaged network devices are unmonitored blind spots.",
    remediation: "Adopt unmanaged network devices into the controller.",
  },
  // GRC -------------------------------------------------------------------
  {
    id: "GRC-001",
    name: "ControlMap Control Completion",
    category: "Compliance",
    capability: "grc",
    source: "ControlMap",
    target: "Framework target",
    criticality: "Medium",
    freshnessThresholdHours: 24 * 7,
    ownerRole: "vCISO",
    populationBased: true,
    businessRisk: "Incomplete controls jeopardize compliance attestations.",
    remediation: "Complete outstanding framework controls.",
  },
  {
    id: "GRC-002",
    name: "Overdue GRC Evidence",
    category: "Compliance",
    capability: "grc",
    source: "ControlMap",
    target: "0 overdue critical",
    criticality: "High",
    freshnessThresholdHours: 24 * 7,
    ownerRole: "vCISO",
    populationBased: false,
    businessRisk: "Overdue evidence fails audits and delays certification.",
    remediation: "Collect and upload overdue control evidence.",
  },
  // Data / platform -------------------------------------------------------
  {
    id: "DATA-001",
    name: "Integration Health",
    category: "Coverage",
    capability: "service_management",
    source: "All",
    target: "100% critical sources",
    criticality: "Critical",
    freshnessThresholdHours: 6,
    ownerRole: "Service Manager",
    populationBased: false,
    businessRisk: "Unhealthy integrations blind Pulse to real conditions.",
    remediation: "Restore failed source integrations.",
  },
  {
    id: "DATA-002",
    name: "Asset Population Reconciliation",
    category: "Coverage",
    capability: "endpoint_management",
    source: "All",
    target: ">=95%",
    criticality: "High",
    freshnessThresholdHours: 24,
    ownerRole: "Service Manager",
    populationBased: true,
    businessRisk: "Population mismatches hide unmanaged or unprotected assets.",
    remediation: "Reconcile asset populations across systems.",
  },
  {
    id: "DATA-003",
    name: "Stale Evidence Rate",
    category: "Coverage",
    capability: "service_management",
    source: "All",
    target: "<2%",
    criticality: "High",
    freshnessThresholdHours: 24,
    ownerRole: "Service Manager",
    populationBased: true,
    businessRisk: "Stale evidence undermines trust in every derived score.",
    remediation: "Refresh stale collectors and confirm connectivity.",
  },
];

export const METRIC_CATALOG: MetricDefinition[] = ROWS.map((r) => ({
  ...r,
  weight: CRITICALITY_WEIGHT[r.criticality],
  version: METRIC_VERSION,
}));

export const METRICS_BY_ID: Record<string, MetricDefinition> = Object.fromEntries(
  METRIC_CATALOG.map((m) => [m.id, m]),
);

export function getMetric(id: string): MetricDefinition {
  const m = METRICS_BY_ID[id];
  if (!m) throw new Error(`Unknown metric: ${id}`);
  return m;
}
